#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>

#define MAX_STRING_LENGTH 100

// Function to generate a random alphanumeric string of given length
void generateRandomString(char *str, int length) {
    static const char charset[] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    for (int i = 0; i < length; ++i) {
        int index = rand() % (sizeof(charset) - 1);
        str[i] = charset[index];
    }
    str[length] = '\0';
}

// Function to check if a string is unique across all processes
int isUnique(char *str, char **allStrings, int totalStrings) {
    for (int i = 0; i < totalStrings; ++i) {
        if (strcmp(str, allStrings[i]) == 0) {
            return 0; // Not unique
        }
    }
    return 1; // Unique
}

int main(int argc, char *argv[]) {
    int rank, size;
    int X = 100; // Total number of strings to generate
    int N = 10; // Maximum length of each string
    int totalStringsPerProcess, remainder;
    char **allStrings = NULL;
    char *myStrings = NULL;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    // Calculate the number of strings to be generated by each process
    totalStringsPerProcess = X / size;
    remainder = X % size;

    // Adjust totalStringsPerProcess for processes with remainder
    if (rank < remainder) {
        totalStringsPerProcess++;
    }

    // Allocate memory for holding all generated strings in each process
    allStrings = (char **)malloc(X * sizeof(char *));
    myStrings = (char *)malloc(totalStringsPerProcess * (MAX_STRING_LENGTH + 1) * sizeof(char));

    // Generate strings for this process
    srand(rank); // Seed the random number generator
    for (int i = 0; i < totalStringsPerProcess; ++i) {
        // Generate a random string of length up to N
        char newString[MAX_STRING_LENGTH + 1];
        generateRandomString(newString, rand() % N + 1);

        // Append rank to ensure uniqueness across processes
        snprintf(newString + strlen(newString), MAX_STRING_LENGTH - strlen(newString), "%d", rank);

        // Check uniqueness within this process
        if (!isUnique(newString, allStrings, i)) {
            i--; // Regenerate if not unique
            continue;
        }

        // Store the generated string
        strcpy(myStrings + i * (MAX_STRING_LENGTH + 1), newString);
    }

    // Gather all generated strings to process 0
    MPI_Gather(myStrings, totalStringsPerProcess * (MAX_STRING_LENGTH + 1), MPI_CHAR,
               allStrings, totalStringsPerProcess * (MAX_STRING_LENGTH + 1), MPI_CHAR,
               0, MPI_COMM_WORLD);

    // Process 0 can now check for uniqueness across all generated strings and finalize the list

    // Cleanup
    free(myStrings);
    free(allStrings);
    
    MPI_Finalize();
    return 0;
}
