#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>

#define MAX_CHAR_SET 62 // Total number of alphanumeric characters

// Function to generate alphanumeric strings
void generate_strings(int process_id, int num_processes, int max_length, int total_strings, char *buffer) {
    char char_set[MAX_CHAR_SET + 1] = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    int string_length;
    int i, j, idx;
    int local_count = 0;
    char str[max_length + 1];

    // Calculate the total number of strings to be generated by each process
    int strings_per_process = total_strings / num_processes;
    if (process_id < total_strings % num_processes) {
        strings_per_process++;
    }

    // Loop through each length of the string
    for (string_length = 1; string_length <= max_length; string_length++) {
        // Calculate the starting index and ending index for this process
        int start_index = (process_id * strings_per_process * MAX_CHAR_SET) / total_strings;
        int end_index = ((process_id + 1) * strings_per_process * MAX_CHAR_SET) / total_strings;

        // Loop through each character in the character set for this process
        for (i = start_index; i < end_index; i++) {
            str[0] = char_set[i % MAX_CHAR_SET];
            // Generate strings of the current length recursively
            for (j = 1; j < string_length; j++) {
                // Calculate the next index for this process
                idx = (process_id * strings_per_process * MAX_CHAR_SET * (string_length - 1)) / total_strings;
                str[j] = char_set[(idx + i) % MAX_CHAR_SET];
            }
            // Copy the generated string to the buffer
            strcpy(buffer + local_count * (max_length + 1), str);
            local_count++;
            if (local_count >= strings_per_process) {
                break;
            }
        }
        if (local_count >= strings_per_process) {
            break;
        }
    }
}

int main(int argc, char *argv[]) {
    int process_id, num_processes;
    int X = 10; // Number of strings to generate
    int N = 3;  // Maximum length of strings
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &process_id);
    MPI_Comm_size(MPI_COMM_WORLD, &num_processes);

    // Allocate buffer to store generated strings on each process
    char *buffer = (char *)malloc(X * N * sizeof(char));

    // Generate strings
    generate_strings(process_id, num_processes, N, X, buffer);

    // Send the counts of strings to process 0
    int counts;
    MPI_Reduce(&X, &counts, 1, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);

    // Send strings from all processes to process 0
    if (process_id != 0) {
        MPI_Send(buffer, X * (N + 1), MPI_CHAR, 0, 0, MPI_COMM_WORLD);
    } else {
        char *recv_buffer = (char *)malloc(counts * (N + 1) * sizeof(char));
        memcpy(recv_buffer, buffer, X * (N + 1) * sizeof(char));
        for (int i = 1; i < num_processes; i++) {
            MPI_Recv(recv_buffer + X * (N + 1) * i, X * (N + 1), MPI_CHAR, i, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
        }

        // Print the strings on process 0
        printf("Generated strings:\n");
        for (int i = 0; i < counts; i++) {
            printf("%s\n", recv_buffer + i * (N + 1));
        }

        free(recv_buffer);
    }

    // Free allocated memory
    free(buffer);

    MPI_Finalize();
    return 0;
}
